name: memo_planner
description: A Flutter application powered by Firebase.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.1.4

environment:
  sdk: ">=3.1.3 <4.0.0"

# run `flutter pub upgrade --major-versions` to upgrade the major versions of your dependencies.
# run `flutter pub outdated` to see which packages are outdated.
dependencies:
  # core + functional
  equatable: ^2.0.5 # functional equality
  dartz: ^0.10.1 # functional programming
  get_it: ^7.6.4 # dependency injection
  injectable: ^2.3.2 # code generator for get_it
  intl: ^0.19.0 # internationalization ^0.18.1 
  timezone: ^0.9.2
  http: ^1.1.2 # http client

  # ui
  # firebase_ui_auth: ^1.9.1
  # font_awesome_flutter: ^10.6.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  # cupertino_icons: ^1.0.2 # Use with the CupertinoIcons class for iOS style icons.

  flutter_native_splash: ^2.3.5 # cmd:dart run flutter_native_splash:create
  flutter_launcher_icons: ^0.13.1 # cmd:flutter pub run flutter_launcher_icons
  flutter_iconpicker: ^3.2.4
  flutter_slidable: ^3.0.1 # swipe
  easy_date_timeline: ^1.0.2 # timeline
  clean_calendar: ^1.1.0 # calendar

  # state management + navigation
  provider: ^6.0.5
  flutter_bloc: ^8.1.3
  go_router: ^14.2.7

  # firebase + google
  googleapis_auth: ^1.4.1 #this package is not compatible with google_sign_in
  extension_google_sign_in_as_googleapis_auth: ^2.0.12
  googleapis: ^13.2.0
  google_sign_in: ^6.1.5
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  cloud_firestore: ^4.9.3
  firebase_storage: ^11.6.0
  firebase_messaging: ^14.7.8

  # storage
  shared_preferences: ^2.2.2
  # drift: ^2.13.0
  # sqlite3_flutter_libs: ^0.5.0

  # maybe use later
  #awesome_flutter_chat
  #stream_chat_flutter

  # notification
  flutter_local_notifications: ^17.2.2
  awesome_snackbar_content: ^0.1.3
  fluttertoast: ^8.2.4
  
  # other
  package_info_plus: ^8.0.2
  url_launcher: ^6.2.3
  image_picker: ^1.0.7

  flutter:
    sdk: flutter

dev_dependencies:
  build_runner:
  change_app_package_name:
  injectable_generator:
  analyzer:
  # drift_dev:
  # mockito: ^5.4.2

  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/avatar/
    - assets/images/icon/
    - assets/images/logo/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
